create sequence "public"."pinned_contacts_id_seq";


  create table "public"."blocks" (
    "id" uuid not null default gen_random_uuid(),
    "blocker_id" uuid not null,
    "blocked_id" uuid not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."blocks" enable row level security;


  create table "public"."devices" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "device_name" text,
    "device_id" text,
    "is_visible" boolean not null default true,
    "last_seen" timestamp with time zone not null default now(),
    "rssi" integer,
    "distance_feet" numeric,
    "action" text,
    "phone_number" text,
    "email" text,
    "bio" text,
    "social_media" jsonb,
    "profile_photo" text
      );


alter table "public"."devices" enable row level security;


  create table "public"."drops" (
    "id" uuid not null default gen_random_uuid(),
    "sender_id" uuid not null,
    "receiver_id" uuid not null,
    "status" text default 'pending'::text,
    "created_at" timestamp with time zone default now(),
    "responded_at" timestamp with time zone,
    "sender_name" text,
    "sender_username" text,
    "sender_email" text,
    "sender_phone" text,
    "sender_bio" text,
    "sender_profile_photo" text,
    "sender_social_media" jsonb,
    "distance_feet" real
      );


alter table "public"."drops" enable row level security;


  create table "public"."links" (
    "id" uuid not null default gen_random_uuid(),
    "user_id_1" uuid not null,
    "user_id_2" uuid not null,
    "drop_id" uuid,
    "created_at" timestamp with time zone default now(),
    "viewed_at" timestamp with time zone
      );


alter table "public"."links" enable row level security;


  create table "public"."pinned_contacts" (
    "id" bigint not null default nextval('public.pinned_contacts_id_seq'::regclass),
    "user_id" uuid not null,
    "contact_user_id" uuid not null,
    "pinned_at" timestamp with time zone not null default now()
      );


alter table "public"."pinned_contacts" enable row level security;


  create table "public"."tutorial_completions" (
    "user_id" uuid not null,
    "home_completed" boolean default false,
    "drop_completed" boolean default false,
    "history_completed" boolean default false,
    "account_completed" boolean default false,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."tutorial_completions" enable row level security;


  create table "public"."user_profiles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "name" text,
    "phone" text,
    "email" text,
    "bio" text,
    "profile_photo" text,
    "social_media" jsonb default '[]'::jsonb,
    "has_completed_onboarding" boolean not null default false,
    "tutorial_home_completed" boolean default false,
    "tutorial_drop_completed" boolean default false,
    "tutorial_history_completed" boolean default false,
    "tutorial_account_completed" boolean default false,
    "phone_verified" boolean default false,
    "phone_verification_code" text,
    "verification_code_expires" timestamp with time zone,
    "username" text,
    "push_token" text
      );


alter table "public"."user_profiles" enable row level security;


  create table "public"."user_settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "dark_mode" boolean not null default true,
    "max_distance" integer not null default 33
      );


alter table "public"."user_settings" enable row level security;

alter sequence "public"."pinned_contacts_id_seq" owned by "public"."pinned_contacts"."id";

CREATE UNIQUE INDEX blocks_blocker_id_blocked_id_key ON public.blocks USING btree (blocker_id, blocked_id);

CREATE UNIQUE INDEX blocks_pkey ON public.blocks USING btree (id);

CREATE UNIQUE INDEX devices_pkey ON public.devices USING btree (id);

CREATE UNIQUE INDEX drops_pkey ON public.drops USING btree (id);

CREATE INDEX idx_drops_created_at ON public.drops USING btree (created_at DESC);

CREATE INDEX idx_drops_receiver_status ON public.drops USING btree (receiver_id, status);

CREATE INDEX idx_drops_sender ON public.drops USING btree (sender_id);

CREATE INDEX idx_user_profiles_phone_verified ON public.user_profiles USING btree (phone_verified);

CREATE UNIQUE INDEX links_pkey ON public.links USING btree (id);

CREATE UNIQUE INDEX pinned_contacts_pkey ON public.pinned_contacts USING btree (id);

CREATE UNIQUE INDEX pinned_contacts_user_id_contact_user_id_key ON public.pinned_contacts USING btree (user_id, contact_user_id);

CREATE UNIQUE INDEX tutorial_completions_pkey ON public.tutorial_completions USING btree (user_id);

CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (id);

CREATE UNIQUE INDEX user_settings_pkey ON public.user_settings USING btree (id);

alter table "public"."blocks" add constraint "blocks_pkey" PRIMARY KEY using index "blocks_pkey";

alter table "public"."devices" add constraint "devices_pkey" PRIMARY KEY using index "devices_pkey";

alter table "public"."drops" add constraint "drops_pkey" PRIMARY KEY using index "drops_pkey";

alter table "public"."links" add constraint "links_pkey" PRIMARY KEY using index "links_pkey";

alter table "public"."pinned_contacts" add constraint "pinned_contacts_pkey" PRIMARY KEY using index "pinned_contacts_pkey";

alter table "public"."tutorial_completions" add constraint "tutorial_completions_pkey" PRIMARY KEY using index "tutorial_completions_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_pkey" PRIMARY KEY using index "user_profiles_pkey";

alter table "public"."user_settings" add constraint "user_settings_pkey" PRIMARY KEY using index "user_settings_pkey";

alter table "public"."blocks" add constraint "blocks_blocker_id_blocked_id_key" UNIQUE using index "blocks_blocker_id_blocked_id_key";

alter table "public"."drops" add constraint "drops_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES auth.users(id) not valid;

alter table "public"."drops" validate constraint "drops_receiver_id_fkey";

alter table "public"."drops" add constraint "drops_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES auth.users(id) not valid;

alter table "public"."drops" validate constraint "drops_sender_id_fkey";

alter table "public"."drops" add constraint "drops_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'linked'::text, 'deleted'::text]))) not valid;

alter table "public"."drops" validate constraint "drops_status_check";

alter table "public"."links" add constraint "links_drop_id_fkey" FOREIGN KEY (drop_id) REFERENCES public.drops(id) ON DELETE SET NULL not valid;

alter table "public"."links" validate constraint "links_drop_id_fkey";

alter table "public"."links" add constraint "links_user_id_1_fkey" FOREIGN KEY (user_id_1) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."links" validate constraint "links_user_id_1_fkey";

alter table "public"."links" add constraint "links_user_id_2_fkey" FOREIGN KEY (user_id_2) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."links" validate constraint "links_user_id_2_fkey";

alter table "public"."pinned_contacts" add constraint "pinned_contacts_contact_user_id_fkey" FOREIGN KEY (contact_user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."pinned_contacts" validate constraint "pinned_contacts_contact_user_id_fkey";

alter table "public"."pinned_contacts" add constraint "pinned_contacts_user_id_contact_user_id_key" UNIQUE using index "pinned_contacts_user_id_contact_user_id_key";

alter table "public"."pinned_contacts" add constraint "pinned_contacts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."pinned_contacts" validate constraint "pinned_contacts_user_id_fkey";

alter table "public"."tutorial_completions" add constraint "tutorial_completions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."tutorial_completions" validate constraint "tutorial_completions_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.delete_user()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  DELETE FROM public.pinned_contacts WHERE user_id = auth.uid();
  DELETE FROM public.links WHERE user_id_1 = auth.uid() OR user_id_2 = auth.uid();
  DELETE FROM public.drops WHERE sender_id = auth.uid() OR receiver_id = auth.uid();
  DELETE FROM public.devices WHERE user_id = auth.uid();
  DELETE FROM public.user_settings WHERE user_id = auth.uid();
  DELETE FROM public.user_profiles WHERE user_id = auth.uid();
  DELETE FROM auth.users WHERE id = auth.uid();
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_contact_profiles(target_ids uuid[])
 RETURNS TABLE(user_id uuid, name text, username text, email text, phone text, bio text, profile_photo text, social_media jsonb)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT up.user_id, up.name, up.username, up.email, up.phone, up.bio, up.profile_photo, up.social_media
  FROM user_profiles up
  WHERE up.user_id = ANY(target_ids)
    AND (
      EXISTS (
        SELECT 1 FROM drops d
        WHERE d.sender_id = up.user_id AND d.receiver_id = auth.uid()
      )
      OR EXISTS (
        SELECT 1 FROM links l
        WHERE (l.user_id_1 = auth.uid() AND l.user_id_2 = up.user_id)
           OR (l.user_id_2 = auth.uid() AND l.user_id_1 = up.user_id)
      )
    );
$function$
;

CREATE OR REPLACE FUNCTION public.get_name_by_email(check_email text)
 RETURNS text
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT name FROM user_profiles WHERE lower(email) = lower(check_email) LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION public.get_profile_by_user_id_prefix(prefix text)
 RETURNS TABLE(user_id uuid, name text, username text)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT user_id, name, username
  FROM user_profiles
  WHERE user_id::text ILIKE prefix || '%'
  LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION public.is_email_taken(check_email text)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (SELECT 1 FROM user_profiles WHERE lower(email) = lower(check_email));
$function$
;

CREATE OR REPLACE FUNCTION public.is_username_taken(check_name text)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (SELECT 1 FROM user_profiles WHERE name = check_name);
$function$
;

grant delete on table "public"."blocks" to "anon";

grant insert on table "public"."blocks" to "anon";

grant references on table "public"."blocks" to "anon";

grant select on table "public"."blocks" to "anon";

grant trigger on table "public"."blocks" to "anon";

grant truncate on table "public"."blocks" to "anon";

grant update on table "public"."blocks" to "anon";

grant delete on table "public"."blocks" to "authenticated";

grant insert on table "public"."blocks" to "authenticated";

grant references on table "public"."blocks" to "authenticated";

grant select on table "public"."blocks" to "authenticated";

grant trigger on table "public"."blocks" to "authenticated";

grant truncate on table "public"."blocks" to "authenticated";

grant update on table "public"."blocks" to "authenticated";

grant delete on table "public"."blocks" to "service_role";

grant insert on table "public"."blocks" to "service_role";

grant references on table "public"."blocks" to "service_role";

grant select on table "public"."blocks" to "service_role";

grant trigger on table "public"."blocks" to "service_role";

grant truncate on table "public"."blocks" to "service_role";

grant update on table "public"."blocks" to "service_role";

grant delete on table "public"."devices" to "anon";

grant insert on table "public"."devices" to "anon";

grant references on table "public"."devices" to "anon";

grant select on table "public"."devices" to "anon";

grant trigger on table "public"."devices" to "anon";

grant truncate on table "public"."devices" to "anon";

grant update on table "public"."devices" to "anon";

grant delete on table "public"."devices" to "authenticated";

grant insert on table "public"."devices" to "authenticated";

grant references on table "public"."devices" to "authenticated";

grant select on table "public"."devices" to "authenticated";

grant trigger on table "public"."devices" to "authenticated";

grant truncate on table "public"."devices" to "authenticated";

grant update on table "public"."devices" to "authenticated";

grant delete on table "public"."devices" to "service_role";

grant insert on table "public"."devices" to "service_role";

grant references on table "public"."devices" to "service_role";

grant select on table "public"."devices" to "service_role";

grant trigger on table "public"."devices" to "service_role";

grant truncate on table "public"."devices" to "service_role";

grant update on table "public"."devices" to "service_role";

grant delete on table "public"."drops" to "anon";

grant insert on table "public"."drops" to "anon";

grant references on table "public"."drops" to "anon";

grant select on table "public"."drops" to "anon";

grant trigger on table "public"."drops" to "anon";

grant truncate on table "public"."drops" to "anon";

grant update on table "public"."drops" to "anon";

grant delete on table "public"."drops" to "authenticated";

grant insert on table "public"."drops" to "authenticated";

grant references on table "public"."drops" to "authenticated";

grant select on table "public"."drops" to "authenticated";

grant trigger on table "public"."drops" to "authenticated";

grant truncate on table "public"."drops" to "authenticated";

grant update on table "public"."drops" to "authenticated";

grant delete on table "public"."drops" to "service_role";

grant insert on table "public"."drops" to "service_role";

grant references on table "public"."drops" to "service_role";

grant select on table "public"."drops" to "service_role";

grant trigger on table "public"."drops" to "service_role";

grant truncate on table "public"."drops" to "service_role";

grant update on table "public"."drops" to "service_role";

grant delete on table "public"."links" to "anon";

grant insert on table "public"."links" to "anon";

grant references on table "public"."links" to "anon";

grant select on table "public"."links" to "anon";

grant trigger on table "public"."links" to "anon";

grant truncate on table "public"."links" to "anon";

grant update on table "public"."links" to "anon";

grant delete on table "public"."links" to "authenticated";

grant insert on table "public"."links" to "authenticated";

grant references on table "public"."links" to "authenticated";

grant select on table "public"."links" to "authenticated";

grant trigger on table "public"."links" to "authenticated";

grant truncate on table "public"."links" to "authenticated";

grant update on table "public"."links" to "authenticated";

grant delete on table "public"."links" to "service_role";

grant insert on table "public"."links" to "service_role";

grant references on table "public"."links" to "service_role";

grant select on table "public"."links" to "service_role";

grant trigger on table "public"."links" to "service_role";

grant truncate on table "public"."links" to "service_role";

grant update on table "public"."links" to "service_role";

grant delete on table "public"."pinned_contacts" to "anon";

grant insert on table "public"."pinned_contacts" to "anon";

grant references on table "public"."pinned_contacts" to "anon";

grant select on table "public"."pinned_contacts" to "anon";

grant trigger on table "public"."pinned_contacts" to "anon";

grant truncate on table "public"."pinned_contacts" to "anon";

grant update on table "public"."pinned_contacts" to "anon";

grant delete on table "public"."pinned_contacts" to "authenticated";

grant insert on table "public"."pinned_contacts" to "authenticated";

grant references on table "public"."pinned_contacts" to "authenticated";

grant select on table "public"."pinned_contacts" to "authenticated";

grant trigger on table "public"."pinned_contacts" to "authenticated";

grant truncate on table "public"."pinned_contacts" to "authenticated";

grant update on table "public"."pinned_contacts" to "authenticated";

grant delete on table "public"."pinned_contacts" to "service_role";

grant insert on table "public"."pinned_contacts" to "service_role";

grant references on table "public"."pinned_contacts" to "service_role";

grant select on table "public"."pinned_contacts" to "service_role";

grant trigger on table "public"."pinned_contacts" to "service_role";

grant truncate on table "public"."pinned_contacts" to "service_role";

grant update on table "public"."pinned_contacts" to "service_role";

grant delete on table "public"."tutorial_completions" to "anon";

grant insert on table "public"."tutorial_completions" to "anon";

grant references on table "public"."tutorial_completions" to "anon";

grant select on table "public"."tutorial_completions" to "anon";

grant trigger on table "public"."tutorial_completions" to "anon";

grant truncate on table "public"."tutorial_completions" to "anon";

grant update on table "public"."tutorial_completions" to "anon";

grant delete on table "public"."tutorial_completions" to "authenticated";

grant insert on table "public"."tutorial_completions" to "authenticated";

grant references on table "public"."tutorial_completions" to "authenticated";

grant select on table "public"."tutorial_completions" to "authenticated";

grant trigger on table "public"."tutorial_completions" to "authenticated";

grant truncate on table "public"."tutorial_completions" to "authenticated";

grant update on table "public"."tutorial_completions" to "authenticated";

grant delete on table "public"."tutorial_completions" to "service_role";

grant insert on table "public"."tutorial_completions" to "service_role";

grant references on table "public"."tutorial_completions" to "service_role";

grant select on table "public"."tutorial_completions" to "service_role";

grant trigger on table "public"."tutorial_completions" to "service_role";

grant truncate on table "public"."tutorial_completions" to "service_role";

grant update on table "public"."tutorial_completions" to "service_role";

grant delete on table "public"."user_profiles" to "anon";

grant insert on table "public"."user_profiles" to "anon";

grant references on table "public"."user_profiles" to "anon";

grant select on table "public"."user_profiles" to "anon";

grant trigger on table "public"."user_profiles" to "anon";

grant truncate on table "public"."user_profiles" to "anon";

grant update on table "public"."user_profiles" to "anon";

grant delete on table "public"."user_profiles" to "authenticated";

grant insert on table "public"."user_profiles" to "authenticated";

grant references on table "public"."user_profiles" to "authenticated";

grant select on table "public"."user_profiles" to "authenticated";

grant trigger on table "public"."user_profiles" to "authenticated";

grant truncate on table "public"."user_profiles" to "authenticated";

grant update on table "public"."user_profiles" to "authenticated";

grant delete on table "public"."user_profiles" to "service_role";

grant insert on table "public"."user_profiles" to "service_role";

grant references on table "public"."user_profiles" to "service_role";

grant select on table "public"."user_profiles" to "service_role";

grant trigger on table "public"."user_profiles" to "service_role";

grant truncate on table "public"."user_profiles" to "service_role";

grant update on table "public"."user_profiles" to "service_role";

grant delete on table "public"."user_settings" to "anon";

grant insert on table "public"."user_settings" to "anon";

grant references on table "public"."user_settings" to "anon";

grant select on table "public"."user_settings" to "anon";

grant trigger on table "public"."user_settings" to "anon";

grant truncate on table "public"."user_settings" to "anon";

grant update on table "public"."user_settings" to "anon";

grant delete on table "public"."user_settings" to "authenticated";

grant insert on table "public"."user_settings" to "authenticated";

grant references on table "public"."user_settings" to "authenticated";

grant select on table "public"."user_settings" to "authenticated";

grant trigger on table "public"."user_settings" to "authenticated";

grant truncate on table "public"."user_settings" to "authenticated";

grant update on table "public"."user_settings" to "authenticated";

grant delete on table "public"."user_settings" to "service_role";

grant insert on table "public"."user_settings" to "service_role";

grant references on table "public"."user_settings" to "service_role";

grant select on table "public"."user_settings" to "service_role";

grant trigger on table "public"."user_settings" to "service_role";

grant truncate on table "public"."user_settings" to "service_role";

grant update on table "public"."user_settings" to "service_role";


  create policy "Users can create their own blocks"
  on "public"."blocks"
  as permissive
  for insert
  to public
with check ((auth.uid() = blocker_id));



  create policy "Users can delete their own blocks"
  on "public"."blocks"
  as permissive
  for delete
  to public
using ((auth.uid() = blocker_id));



  create policy "Users can view blocks involving them"
  on "public"."blocks"
  as permissive
  for select
  to public
using (((auth.uid() = blocker_id) OR (auth.uid() = blocked_id)));



  create policy "Users can delete own devices"
  on "public"."devices"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "users can insert own devices"
  on "public"."devices"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "users can read own devices"
  on "public"."devices"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "users can update own devices"
  on "public"."devices"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id));



  create policy "Users can delete own drops"
  on "public"."drops"
  as permissive
  for delete
  to public
using (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)));



  create policy "Users can respond to received drops"
  on "public"."drops"
  as permissive
  for update
  to public
using ((auth.uid() = receiver_id));



  create policy "Users can send drops"
  on "public"."drops"
  as permissive
  for insert
  to public
with check ((auth.uid() = sender_id));



  create policy "Users can update their own drops"
  on "public"."drops"
  as permissive
  for update
  to public
using (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)));



  create policy "Users can view their own drops"
  on "public"."drops"
  as permissive
  for select
  to public
using (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)));



  create policy "Users can delete own links"
  on "public"."links"
  as permissive
  for delete
  to public
using (((auth.uid() = user_id_1) OR (auth.uid() = user_id_2)));



  create policy "Users can insert links"
  on "public"."links"
  as permissive
  for insert
  to public
with check (((auth.uid() = user_id_1) OR (auth.uid() = user_id_2)));



  create policy "Users can update their own links."
  on "public"."links"
  as permissive
  for update
  to public
using (((auth.uid() = user_id_1) OR (auth.uid() = user_id_2)))
with check (((auth.uid() = user_id_1) OR (auth.uid() = user_id_2)));



  create policy "Users can view their own links"
  on "public"."links"
  as permissive
  for select
  to public
using (((auth.uid() = user_id_1) OR (auth.uid() = user_id_2)));



  create policy "Users can pin contacts"
  on "public"."pinned_contacts"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Users can unpin contacts"
  on "public"."pinned_contacts"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "Users can view own pinned contacts"
  on "public"."pinned_contacts"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "Manage tutorial completion"
  on "public"."tutorial_completions"
  as permissive
  for all
  to public
using ((auth.uid() = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."user_profiles"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Users can delete own profile"
  on "public"."user_profiles"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can read own profile"
  on "public"."user_profiles"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "allow_update_own_profile"
  on "public"."user_profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Users can delete own settings"
  on "public"."user_settings"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "users can insert own settings"
  on "public"."user_settings"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "users can read own settings"
  on "public"."user_settings"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "users can update own settings "
  on "public"."user_settings"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id));


CREATE TRIGGER "drop-linked-notification" AFTER UPDATE ON public.drops FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://jfuhplqtujaakksmixii.supabase.co/functions/v1/send-drop-notification', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmdWhwbHF0dWphYWtrc21peGlpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mzk2OTQ3MSwiZXhwIjoyMDc5NTQ1NDcxfQ.JykihT_PpPfxgjhyvyusQBkK-2isetm9WhdqOYjYj3I"}', '{}', '5000');

CREATE TRIGGER "drops-inserted-notification" AFTER INSERT ON public.drops FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://jfuhplqtujaakksmixii.supabase.co/functions/v1/send-drop-notification', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmdWhwbHF0dWphYWtrc21peGlpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mzk2OTQ3MSwiZXhwIjoyMDc5NTQ1NDcxfQ.JykihT_PpPfxgjhyvyusQBkK-2isetm9WhdqOYjYj3I"}', '{}', '5000');


  create policy "users_own_folder"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using (((bucket_id = 'profile_photos'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



