name: Database Backup

on:
  schedule:
    # Run daily at 3:00 AM UTC
    - cron: '0 3 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  backup-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install cloudinary psycopg2-binary
      
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      
      - name: Backup PostgreSQL database
        env:
          DATABASE_URL: ${{ secrets.RAILWAY_DATABASE_URL }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: |
          python backend/backup-postgres.py
      
      - name: Cleanup old backups
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: |
          python backend/cleanup-old-backups.py
      
      - name: Send success notification
        if: success()
        run: |
          echo "Backup completed successfully at $(date)"
      
      - name: Send failure notification
        if: failure()
        run: |
          echo "Backup failed at $(date)"
          echo "Check workflow logs for details"
          # TODO: Add email/Slack notification here

