name: EAS Update on Push
on:
  push:
    branches: 
      - develop
jobs:
  update:
    name: Publish EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: mobile/package-lock.json
          
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Install dependencies
        working-directory: mobile
        run: npm ci
        
      - name: Publish update
        working-directory: mobile
        run: eas update --auto --branch preview --message "${{ github.event.head_commit.message }}"

